apiVersion: v1
kind: Service
metadata:
  name: api-monitor
  labels:
    app.kubernetes.io/name: api-monitor
spec:
  selector:
    app.kubernetes.io/name: api-monitor
  ports:
    - name: http
      port: 8765
      targetPort: http
