apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: data-warehouse
  labels:
    app: minio
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 500Gi
