apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part-of: bifrost
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespaces.yaml
  - ai/ollama-pvc.yaml
  - ai/ollama.yaml
  - warehouse/minio-pvc.yaml
  - warehouse/minio.yaml
