apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bifrost-platform-prod

resources:
  - namespace.yaml
  - ../../base-platform
  - ops-ingressroute.yaml
  - ops-http-redirect.yaml

configMapGenerator:
  - name: bifrost-platform-config
    files:
      - config/environments.yaml
      - config/clusters.yaml
      - config/topology.yaml
      - config/ops-context.yaml
      - config/platform-auth.yaml
    options:
      disableNameSuffixHash: true
  - name: bifrost-platform-programs
    files:
      - config/programs/_schema.yaml
      - config/programs/dap-smoke-test.yaml
      - config/programs/example-template.yaml
      - config/programs/trade-ib-client-migration.yaml
    options:
      disableNameSuffixHash: true

patches:
  - path: images-pull-always.patch.yaml
  - path: replicas-ha.patch.yaml
  - path: nodeport-prod.patch.yaml
  - path: platform-api-agent-bridge-env.patch.yaml

images:
  - name: registry.cicd.svc.cluster.local:5000/bifrost-platform-api
    newName: 192.168.10.73:30500/bifrost-platform-api
    newTag: prod
  - name: registry.cicd.svc.cluster.local:5000/bifrost-platform-console
    newName: 192.168.10.73:30500/bifrost-platform-console
    newTag: prod

commonAnnotations:
  bifrost.io/environment: platform-prod

labels:
  - pairs:
      bifrost.io/environment: platform-prod
    includeSelectors: false
