apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-deliver
  namespace: cicd
  labels:
    bifrost.io/purpose: stg-deliver
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-deliver-argocd
  namespace: cicd
rules:
  - apiGroups: [argoproj.io]
    resources: [applications]
    verbs: [get, patch, list]
  - apiGroups: [""]
    resources: [configmaps]
    verbs: [get, create, patch, update, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-deliver-argocd
  namespace: cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-deliver-argocd
subjects:
  - kind: ServiceAccount
    name: tekton-deliver
    namespace: cicd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-deliver-rollout
  namespace: bifrost-stg
rules:
  - apiGroups: [apps]
    resources: [deployments]
    verbs: [get, patch, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-deliver-rollout
  namespace: bifrost-stg
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-deliver-rollout
subjects:
  - kind: ServiceAccount
    name: tekton-deliver
    namespace: cicd
