#!/usr/bin/env python3
"""Generate k8s/platform-rbac/{10-stg,20-prod}.yaml (TD-204) from one namespace list.

STG observes, PROD maintains (Owner 2026-10-07). The ClusterRoles live in
00-clusterroles.yaml; this writes the ServiceAccount and bindings per env.
Usage: python3 scripts/gen_platform_rbac.py   (then kubectl apply -k k8s/platform-rbac)
"""
import pathlib

OUT = pathlib.Path(__file__).resolve().parent.parent / "k8s" / "platform-rbac"
# Namespaces the platform reads logs in and (PROD) acts on.
BIFROST_NS = ["bifrost-dev", "bifrost-stg", "bifrost-prod", "bifrost-platform-stg", "bifrost-platform-prod",
              "data", "research", "plugin-market-data", "plugin-flex-query", "cicd", "monitoring"]


def sa(env):
    return (f"apiVersion: v1\nkind: ServiceAccount\nmetadata:\n  name: bifrost-platform\n"
            f"  namespace: bifrost-platform-{env}\n  labels: {{app.kubernetes.io/part-of: bifrost-platform}}\n")


def subj(env):
    return f"[{{kind: ServiceAccount, name: bifrost-platform, namespace: bifrost-platform-{env}}}]"


def crb(env, role):
    return (f"apiVersion: rbac.authorization.k8s.io/v1\nkind: ClusterRoleBinding\nmetadata:\n  name: {role}-{env}\n"
            f"  labels: {{app.kubernetes.io/part-of: bifrost-platform}}\n"
            f"roleRef: {{apiGroup: rbac.authorization.k8s.io, kind: ClusterRole, name: {role}}}\nsubjects: {subj(env)}\n")


def rb(env, role, ns):
    return (f"apiVersion: rbac.authorization.k8s.io/v1\nkind: RoleBinding\nmetadata:\n  name: {role}-{env}\n"
            f"  namespace: {ns}\n  labels: {{app.kubernetes.io/part-of: bifrost-platform}}\n"
            f"roleRef: {{apiGroup: rbac.authorization.k8s.io, kind: ClusterRole, name: {role}}}\nsubjects: {subj(env)}\n")


def env_file(env, prod):
    own = f"bifrost-platform-{env}"
    docs = [sa(env), crb(env, "bifrost-platform-observer")]
    docs += [rb(env, "bifrost-platform-logs", n) for n in BIFROST_NS]
    docs += [rb(env, "bifrost-platform-state", own), rb(env, "bifrost-platform-state", "cicd"),
             rb(env, "bifrost-platform-gitea-creds", "cicd")]
    if prod:
        docs += [rb(env, "bifrost-platform-workload-actuator", n) for n in BIFROST_NS]
        docs += [crb(env, "bifrost-platform-node-actuator"), crb(env, "bifrost-platform-node-drain"),
                 rb(env, "bifrost-platform-data-actuator", "data"),
                 rb(env, "bifrost-platform-delivery", "cicd")]
    what = "observe and maintain" if prod else "observe only (Owner 2026-10-07: STG observes, PROD maintains)"
    head = (f"# {env.upper()}: {what}. Generated by\n"
            "# scripts/gen_platform_rbac.py from one namespace list; do not edit by hand.\n")
    return head + "---\n" + "---\n".join(docs)


if __name__ == "__main__":
    (OUT / "10-stg.yaml").write_text(env_file("stg", False))
    (OUT / "20-prod.yaml").write_text(env_file("prod", True))
    print("wrote", OUT / "10-stg.yaml", OUT / "20-prod.yaml")
