apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - cronjob.yaml

configMapGenerator:
  - name: maintainer-reconcile
    files:
      - reconcile.py
      - MAINTAINERS.yaml
    options:
      disableNameSuffixHash: true

labels:
  - pairs:
      app.kubernetes.io/name: maintainer-reconcile
      app.kubernetes.io/part-of: bifrost
    includeSelectors: false
