apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bifrost-platform-stg

labels:
  - pairs:
      app.kubernetes.io/part-of: bifrost-platform
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true

resources:
  - manifest.yaml
